import { PatientMember } from './types';

export const INITIAL_PATIENTS: PatientMember[] = [
  {
    id: '1',
    name: 'Rathi Vijay Sharma',
    relation: 'Self',
    sex: 'M',
    age: '34 Y',
    maritalStatus: 'Married',
    registrationStatus: 'Registered',
    mobileNumber: '9414023873',
    patientNumber: '109282827',
    genderType: 'M',
    dob: '1992-05-14',
    patientType: 'OP',
  },
  {
    id: '2',
    name: 'Kavita Chouhan',
    relation: 'Wife',
    sex: 'F',
    age: '28 Y',
    maritalStatus: 'Married',
    registrationStatus: 'Registered',
    mobileNumber: '73737377374',
    patientNumber: '109282829',
    genderType: 'F',
    dob: '1998-08-22',
    patientType: 'OP',
  },
  {
    id: '3',
    name: 'Aarav Chouhan',
    relation: 'Son',
    sex: 'M',
    age: '8 Y',
    maritalStatus: 'Single',
    registrationStatus: 'Registered',
    mobileNumber: '73737377375',
    patientNumber: '109282830',
    genderType: 'M',
    dob: '2018-03-10',
    patientType: 'OP',
  },
  {
    id: '4',
    name: 'Deepak Chouhan',
    relation: 'Brother',
    sex: 'M',
    age: '30 Y',
    maritalStatus: 'Married',
    registrationStatus: 'Registered',
    mobileNumber: '73737377373',
    patientNumber: '109282828',
    genderType: 'M',
    dob: '1996-11-05',
    patientType: 'OP',
  },
  {
    id: '5',
    name: 'Chandan Chouhan',
    relation: 'Father',
    sex: 'M',
    age: '62 Y',
    maritalStatus: 'Married',
    registrationStatus: 'Registered',
    mobileNumber: '9414023873',
    patientNumber: '109282835',
    ipNo: 'IP-2026-9041',
    genderType: 'M',
    dob: '1962-04-12',
    patientType: 'IP',
    bedNumber: 'Bed 304 (Ward 4A)',
  },
];
