import { PatientMember } from './types';

export const INITIAL_PATIENTS: PatientMember[] = [
  {
    id: '1',
    name: 'CHOUGULE MINAL SACHIN',
    relation: 'Son',
    sex: 'M',
    age: '7yrs',
    maritalStatus: '',
    registrationStatus: 'Registered',
    mobileNumber: '9819863084',
    patientNumber: '1113227',
    genderType: 'M',
  },
  {
    id: '2',
    name: 'SACHIN RAMESH CHOUGULE',
    relation: 'Self',
    sex: 'M',
    age: '38yrs',
    maritalStatus: 'Married',
    registrationStatus: 'Registered',
    mobileNumber: '9819863084',
    patientNumber: '1370485',
    genderType: 'M',
  },
  {
    id: '3',
    name: 'PRIYA SACHIN CHOUGULE',
    relation: 'Spouse',
    sex: 'F',
    age: '34yrs',
    maritalStatus: 'Married',
    registrationStatus: 'Registered',
    mobileNumber: '9819863084',
    patientNumber: '2012468',
    genderType: 'F',
  },
  {
    id: '4',
    name: 'ANANYA SACHIN CHOUGULE',
    relation: 'Daughter',
    sex: 'F',
    age: '5yrs',
    maritalStatus: '',
    registrationStatus: 'Registered',
    mobileNumber: '9819863084',
    patientNumber: '2198473',
    genderType: 'F',
  },
  {
    id: '5',
    name: 'RAMESH DATTATRAY CHOUGULE',
    relation: 'Father',
    sex: 'M',
    age: '64yrs',
    maritalStatus: 'Married',
    registrationStatus: 'Registered',
    mobileNumber: '9876543210',
    patientNumber: '1098234',
    genderType: 'M',
  },
  {
    id: '6',
    name: 'SUNITA RAMESH CHOUGULE',
    relation: 'Mother',
    sex: 'F',
    age: '60yrs',
    maritalStatus: 'Married',
    registrationStatus: 'Registered',
    mobileNumber: '9876543210',
    patientNumber: '1045892',
    genderType: 'F',
  },
  {
    id: '7',
    name: 'ROHAN RAMESH CHOUGULE',
    relation: 'Brother',
    sex: 'M',
    age: '31yrs',
    maritalStatus: 'Married',
    registrationStatus: 'Registered',
    mobileNumber: '9820145678',
    patientNumber: '1540912',
    genderType: 'M',
  },
];
