import { PatientMember } from './types';

export const INITIAL_PATIENTS: PatientMember[] = [
  {
    id: '1',
    name: 'Rathi Vijay Sharma',
    relation: 'Self',
    sex: 'M',
    age: '34 Y',
    maritalStatus: 'Married',
    registrationStatus: 'Registered',
    mobileNumber: '9414023873',
    patientNumber: '109282827',
    genderType: 'M',
  },
  {
    id: '2',
    name: 'Kavita Chouhan',
    relation: 'Wife',
    sex: 'F',
    age: '28 Y',
    maritalStatus: 'Married',
    registrationStatus: 'Registered',
    mobileNumber: '73737377374',
    patientNumber: '109282829',
    genderType: 'F',
  },
  {
    id: '3',
    name: 'Aarav Chouhan',
    relation: 'Son',
    sex: 'M',
    age: '8 Y',
    maritalStatus: '',
    registrationStatus: 'Registered',
    mobileNumber: '73737377375',
    patientNumber: '109282830',
    genderType: 'M',
  },
  {
    id: '4',
    name: 'Deepak Chouhan',
    relation: 'Brother',
    sex: 'M',
    age: '30 Y',
    maritalStatus: 'Married',
    registrationStatus: 'Registered',
    mobileNumber: '73737377373',
    patientNumber: '109282828',
    genderType: 'M',
  },
];
